# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_of_entry', models.DateTimeField()),
                ('date_time_of_exit', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose_of_visit',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.Visitor'),
        ),
    ]
