# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0002_auto_20180201_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
