# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0003_visitor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
