# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0005_auto_20180210_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_time_of_exit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
